from __future__ import annotations

import re

from knowledge_producer import Paper

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    # --- LLM Core ---
    "Pretraining": [
        "pretraining",
        "pre-training",
        "language modeling",
        "scaling law",
        "foundation model",
        "large language model",
        "curriculum learning",
        "next token prediction",
        "causal language model",
        "masked language model",
        "tokenization",
        "tokenizer",
        "vocabulary",
        "byte pair encoding",
        "data mixture",
    ],
    "SFT": [
        "supervised fine-tuning",
        "fine-tuning",
        "instruction tuning",
        "lora",
        "qlora",
        "adapter",
        "peft",
        "parameter-efficient",
        "training data",
        "dataset curation",
        "finetuning",
        "instruction following",
        "chat template",
        "dora",
    ],
    "RL": [
        "reinforcement learning",
        "rlhf",
        "ppo",
        "dpo",
        "grpo",
        "reward model",
        "policy optimization",
        "preference learning",
        "human feedback",
        "rlaif",
        "reward shaping",
        "value function",
        "preference optimization",
        "constitutional ai",
        "reward hacking",
        "online rl",
        "offline rl",
        "inverse reinforcement",
        "multi-armed bandit",
        "policy gradient",
        "q-learning",
        "actor-critic",
    ],
    "Alignment": [
        "alignment",
        "safety alignment",
        "ai safety",
        "red teaming",
        "jailbreak",
        "guardrail",
        "harmful content",
        "toxicity",
        "bias mitigation",
        "fairness",
        "responsible ai",
        "trustworthy",
        "value alignment",
        "refusal",
        "content moderation",
        "ai ethics",
        "watermark",
    ],
    "Inference": [
        "inference optimization",
        "model serving",
        "quantization",
        "pruning",
        "distillation",
        "latency",
        "throughput",
        "kv cache",
        "speculative decoding",
        "deployment",
        "gguf",
        "vllm",
        "tensorrt",
        "onnx",
        "efficient inference",
        "acceleration",
        "token generation",
        "model compression",
        "edge deployment",
        "batch inference",
        "continuous batching",
        "flash attention",
        "mixture of experts",
        "sparse inference",
    ],
    "Architecture": [
        "transformer",
        "attention mechanism",
        "self-attention",
        "linear attention",
        "state space model",
        "mamba",
        "recurrent",
        "positional encoding",
        "rotary embedding",
        "mixture of experts",
        "sparse mixture",
        "multi-head attention",
        "group query attention",
        "sliding window attention",
        "long context",
        "context window",
        "memory augmented",
        "hybrid architecture",
        "sub-quadratic",
        "ring attention",
    ],
    "RAG": [
        "retrieval augmented generation",
        "retrieval-augmented",
        "vector database",
        "embedding model",
        "dense retrieval",
        "semantic search",
        "knowledge retrieval",
        "document retrieval",
        "chunking strategy",
        "reranking",
        "reranker",
        "hybrid search",
        "knowledge base",
        "grounding",
        "hallucination reduction",
    ],
    "Agent": [
        "llm agent",
        "ai agent",
        "tool use",
        "function calling",
        "multi-agent",
        "agentic",
        "self-reflection",
        "tool-augmented",
        "web agent",
        "agent framework",
        "task planning",
        "agent workflow",
        "agent memory",
        "computer use",
        "browser agent",
    ],
    "Coding": [
        "code generation",
        "code completion",
        "code review",
        "code llm",
        "program synthesis",
        "code repair",
        "automated programming",
        "software engineering",
        "code reasoning",
        "code translation",
        "code summarization",
        "unit test generation",
        "code debug",
        "repository-level",
        "code agent",
        "coding benchmark",
        "swe-bench",
    ],
    "Reasoning": [
        "chain-of-thought",
        "mathematical reasoning",
        "logical reasoning",
        "step-by-step",
        "tree of thought",
        "reasoning chain",
        "theorem proving",
        "formal verification",
        "symbolic reasoning",
        "commonsense reasoning",
        "causal reasoning",
        "abstraction",
        "planning",
        "problem solving",
        "arithmetic reasoning",
        "compositional reasoning",
        "test-time compute",
    ],
    "Evaluation": [
        "benchmark",
        "evaluation metric",
        "leaderboard",
        "human evaluation",
        "automatic evaluation",
        "llm-as-judge",
        "model comparison",
        "ablation study",
        "reproducibility",
        "contamination",
        "data leakage",
    ],

    # --- Multimodal & Vision ---
    "Multimodal": [
        "multimodal",
        "multi-modal",
        "vision-language",
        "visual question answering",
        "image captioning",
        "image-text",
        "clip",
        "visual grounding",
        "visual reasoning",
        "video understanding",
        "audio-visual",
        "cross-modal",
        "vision encoder",
        "visual instruction tuning",
        "omni-modal",
        "any-to-any",
        "visual tokenizer",
    ],
    "CV": [
        "object detection",
        "image classification",
        "image segmentation",
        "semantic segmentation",
        "instance segmentation",
        "panoptic segmentation",
        "pose estimation",
        "action recognition",
        "visual tracking",
        "image restoration",
        "super resolution",
        "depth estimation",
        "optical flow",
        "feature extraction",
        "backbone network",
        "convolutional neural",
        "vision transformer",
        "image recognition",
        "face recognition",
        "video classification",
    ],
    "Diffusion": [
        "diffusion model",
        "stable diffusion",
        "image generation",
        "text-to-image",
        "text-to-video",
        "image editing",
        "inpainting",
        "denoising",
        "score matching",
        "flow matching",
        "consistency model",
        "controllable generation",
        "image synthesis",
        "video generation",
        "video synthesis",
        "rectified flow",
        "sdxl",
        "dit",
        "latent diffusion",
    ],
    "3D": [
        "nerf",
        "neural radiance",
        "3d reconstruction",
        "point cloud",
        "3d generation",
        "gaussian splatting",
        "mesh reconstruction",
        "3d object detection",
        "3d scene",
        "volumetric",
        "implicit representation",
        "shape generation",
        "3d-aware",
        "novel view synthesis",
        "3d gaussian",
        "multi-view",
    ],

    # --- Domain Applications ---
    "Autonomous Driving": [
        "autonomous driving",
        "self-driving",
        "autonomous vehicle",
        "lidar",
        "ego vehicle",
        "trajectory prediction",
        "motion planning",
        "lane detection",
        "traffic sign",
        "pedestrian detection",
        "driving scenario",
        "end-to-end driving",
        "vehicle detection",
        "bird's eye view",
        "occupancy prediction",
        "waymo",
        "nuscenes",
        "carla",
        "driving simulation",
    ],
    "Medical": [
        "medical imaging",
        "clinical nlp",
        "drug discovery",
        "biomedical",
        "pathology",
        "radiology",
        "electronic health record",
        "medical diagnosis",
        "medical question answering",
        "protein structure",
        "genomic",
        "clinical trial",
        "health care",
        "healthcare",
        "medical report",
        "chest x-ray",
        "medical llm",
        "surgical",
    ],
    "Science": [
        "scientific discovery",
        "protein folding",
        "molecular",
        "material science",
        "climate model",
        "weather prediction",
        "physics simulation",
        "chemical",
        "drug design",
        "scientific reasoning",
        "ai for science",
        "ai4science",
        "computational biology",
        "neural operator",
        "pde",
        "fluid dynamics",
    ],
    "Robotics": [
        "robotic",
        "robot learning",
        "manipulation",
        "embodied ai",
        "embodied agent",
        "sim-to-real",
        "locomotion",
        "grasping",
        "robot navigation",
        "robot planning",
        "imitation learning",
        "teleoperation",
        "dexterous",
        "humanoid",
        "visuomotor",
        "robot policy",
    ],

    # --- NLP & Speech ---
    "NLP": [
        "named entity",
        "sentiment analysis",
        "text classification",
        "machine translation",
        "summarization",
        "question answering",
        "information extraction",
        "relation extraction",
        "text generation",
        "dialogue system",
        "conversational",
        "coreference",
        "dependency parsing",
        "semantic parsing",
        "natural language understanding",
        "natural language inference",
        "document understanding",
        "multilingual",
    ],
    "Speech": [
        "speech recognition",
        "text-to-speech",
        "automatic speech",
        "voice cloning",
        "speaker verification",
        "speaker diarization",
        "speech synthesis",
        "speech translation",
        "audio generation",
        "music generation",
        "sound event",
        "audio classification",
        "whisper",
        "voice conversion",
        "acoustic model",
        "speech enhancement",
    ],

    # --- Data & Infrastructure ---
    "Data": [
        "synthetic data",
        "data augmentation",
        "data annotation",
        "data labeling",
        "data quality",
        "data filtering",
        "data selection",
        "dataset construction",
        "active learning",
        "self-training",
        "pseudo label",
        "data contamination",
        "web crawl",
        "data deduplication",
        "data preprocessing",
    ],
    "Training": [
        "distributed training",
        "mixed precision",
        "gradient checkpoint",
        "model parallel",
        "data parallel",
        "tensor parallel",
        "pipeline parallel",
        "deepspeed",
        "fsdp",
        "megatron",
        "training efficiency",
        "learning rate",
        "optimizer",
        "loss function",
        "training stability",
        "gradient accumulation",
        "batch size",
    ],

    # --- Other ML Domains ---
    "Graph": [
        "graph neural network",
        "knowledge graph",
        "graph transformer",
        "node classification",
        "link prediction",
        "graph generation",
        "message passing",
        "graph convolution",
        "heterogeneous graph",
        "temporal graph",
        "scene graph",
        "graph reasoning",
    ],
    "Recommendation": [
        "recommendation system",
        "collaborative filtering",
        "click-through rate",
        "user modeling",
        "item embedding",
        "sequential recommendation",
        "conversational recommendation",
        "llm for recommendation",
        "cold start",
    ],
    "Time Series": [
        "time series",
        "forecasting",
        "anomaly detection",
        "temporal modeling",
        "time series classification",
        "time series generation",
        "temporal pattern",
        "seasonal",
        "financial prediction",
        "stock prediction",
    ],
    "Security": [
        "adversarial attack",
        "adversarial robustness",
        "model extraction",
        "membership inference",
        "data poisoning",
        "backdoor attack",
        "federated learning",
        "differential privacy",
        "privacy preserving",
        "model stealing",
        "prompt injection",
        "machine unlearning",
    ],
}

_SHORT_KEYWORD_THRESHOLD = 5


def _match_keyword(keyword: str, text: str) -> bool:
    """Match keyword in text. Uses word-boundary regex for short keywords."""
    if len(keyword) < _SHORT_KEYWORD_THRESHOLD:
        return bool(re.search(r"\b" + re.escape(keyword) + r"\b", text))
    return keyword in text


def categorize_paper(paper: Paper) -> list[str]:
    """Assign category tags to a paper based on keyword matching."""
    text = f"{paper.title} {paper.abstract}".lower()
    matched: list[str] = []
    for category, keywords in CATEGORY_KEYWORDS.items():
        if any(_match_keyword(kw, text) for kw in keywords):
            matched.append(category)
    return matched


def categorize_papers(papers: list[Paper]) -> list[Paper]:
    """Apply categorization to all papers, populating each paper's tags field."""
    for paper in papers:
        paper.tags = categorize_paper(paper)
    return papers
