from __future__ import annotations

import os
from collections import Counter, defaultdict
from datetime import datetime, timezone

from knowledge_producer import Paper

CATEGORY_ORDER = [
    # LLM Core
    "Pretraining", "SFT", "RL", "Alignment", "Inference", "Architecture",
    "RAG", "Agent", "Coding", "Reasoning", "Evaluation",
    # Multimodal & Vision
    "Multimodal", "CV", "Diffusion", "3D",
    # Domain Applications
    "Autonomous Driving", "Medical", "Science", "Robotics",
    # NLP & Speech
    "NLP", "Speech",
    # Data & Infrastructure
    "Data", "Training",
    # Other ML
    "Graph", "Recommendation", "Time Series", "Security",
]


def _format_authors(authors: list[str], max_authors: int = 5) -> str:
    if not authors:
        return "Unknown"
    if len(authors) <= max_authors:
        return ", ".join(authors)
    return ", ".join(authors[:max_authors]) + " et al."


def _paper_section(paper: Paper) -> str:
    authors_str = _format_authors(paper.authors)
    tags_str = ", ".join(paper.tags) if paper.tags else "Uncategorized"
    lines = [
        f"### {paper.title}",
        f"- **Source**: {paper.source}",
        f"- **Link**: {paper.url}",
        f"- **Tags**: {tags_str}",
        f"- **Authors**: {authors_str}",
        f"- **Published**: {paper.published.strftime('%Y-%m-%d')}",
        f"- **Abstract**: {paper.abstract}" if paper.abstract else "",
        "",
        "---",
        "",
    ]
    return "\n".join(line for line in lines if line is not None)


def _paper_section_with_summary(paper: Paper, relevance_summary: str) -> str:
    """Format a focus paper section with an LLM-generated relevance summary."""
    authors_str = _format_authors(paper.authors)
    tags_str = ", ".join(paper.tags) if paper.tags else "Uncategorized"
    lines = [f"### {paper.title}"]
    if relevance_summary:
        lines.append(f"> **Why it matters** *(AI-generated)*: {relevance_summary}")
        lines.append("")
    lines.extend([
        f"- **Source**: {paper.source}",
        f"- **Link**: {paper.url}",
        f"- **Tags**: {tags_str}",
        f"- **Authors**: {authors_str}",
        f"- **Published**: {paper.published.strftime('%Y-%m-%d')}",
    ])
    if paper.abstract:
        lines.append(f"- **Abstract**: {paper.abstract}")
    lines.extend(["", "---", ""])
    return "\n".join(lines)


def generate_report(
    papers: list[Paper],
    report_date: str,
    focus_matches: dict[str, list[Paper]] | None = None,
    enriched_focus: dict[str, list[tuple[Paper, str]]] | None = None,
    generation_info: dict[str, str | int] | None = None,
) -> str:
    """Generate a full Markdown report from categorized papers."""
    lines: list[str] = []

    # Header
    lines.append(f"# AI Research Daily Report - {report_date}")
    lines.append("")

    # Generation info
    if generation_info:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        parts = [f"`days={generation_info['days']}`"]
        parts.append(f"`sources={generation_info['sources']}`")
        parts.append(f"`max_results={generation_info['max_results']}`")
        parts.append(f"`dedup={generation_info.get('dedup', 'off')}`")
        parts.append(f"`focus={generation_info['focus']}`")
        parts.append(f"`llm={generation_info['llm']}`")
        lines.append(f"> Generated on {now} | {' '.join(parts)}")

        # AI disclaimer
        llm_provider = str(generation_info.get("llm", "none"))
        if enriched_focus and llm_provider not in ("disabled", "none", ""):
            provider_label = {"openai": "OpenAI gpt-4o-mini", "anthropic": "Anthropic claude-haiku-4-5"}.get(llm_provider, llm_provider)
            lines.append(f">")
            lines.append(f"> *\"Why it matters\" summaries are AI-generated by {provider_label}.*")

        lines.append("")

    # Summary — category counts
    category_counts = {cat: 0 for cat in CATEGORY_ORDER}
    uncategorized_count = 0
    for paper in papers:
        if not paper.tags:
            uncategorized_count += 1
        for tag in paper.tags:
            if tag in category_counts:
                category_counts[tag] += 1

    cat_stats = " | ".join(f"{cat}: {count}" for cat, count in category_counts.items())

    # Summary — source counts
    source_counts = Counter(p.source for p in papers)
    src_stats = " | ".join(f"{src}: {cnt}" for src, cnt in sorted(source_counts.items()))

    lines.append("## Summary")
    lines.append(f"- **Total items**: {len(papers)}")
    lines.append(f"- **By category**: {cat_stats} | Uncategorized: {uncategorized_count}")
    lines.append(f"- **By source**: {src_stats}")
    if focus_matches:
        focus_stats = " | ".join(f"{t}: {len(p)}" for t, p in focus_matches.items())
        lines.append(f"- **Focus topics**: {focus_stats}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Focus sections — highlighted at the top
    if focus_matches:
        for topic, matched_papers in focus_matches.items():
            lines.append(f"## >> Focus: {topic} ({len(matched_papers)} papers)")
            lines.append("")
            if not matched_papers:
                lines.append("*No papers found for this focus topic.*")
                lines.append("")
            elif enriched_focus and topic in enriched_focus:
                # Use LLM-enriched output with relevance summaries
                for paper, summary in enriched_focus[topic]:
                    lines.append(_paper_section_with_summary(paper, summary))
            else:
                for paper in matched_papers:
                    lines.append(_paper_section(paper))
        lines.append("---")
        lines.append("")
        lines.append("# All Categories")
        lines.append("")

    # Group papers by category
    category_papers: dict[str, list[Paper]] = defaultdict(list)
    uncategorized: list[Paper] = []

    for paper in papers:
        if not paper.tags:
            uncategorized.append(paper)
        else:
            for tag in paper.tags:
                category_papers[tag].append(paper)

    # Category sections
    for category in CATEGORY_ORDER:
        cat_papers = category_papers.get(category, [])
        lines.append(f"## {category} ({len(cat_papers)} papers)")
        lines.append("")
        if not cat_papers:
            lines.append("*No papers found in this category.*")
            lines.append("")
        else:
            for paper in cat_papers:
                lines.append(_paper_section(paper))

    # Uncategorized section
    if uncategorized:
        lines.append(f"## Uncategorized ({len(uncategorized)} papers)")
        lines.append("")
        for paper in uncategorized:
            lines.append(_paper_section(paper))

    # Footer
    lines.append("---")
    lines.append(f"*Generated by knowledge-producer v0.1.0*")
    lines.append("")

    return "\n".join(lines)


def save_report(
    content: str,
    output_dir: str = "reports",
    report_date: str | None = None,
    days: int = 1,
) -> str:
    """Write the report to a file and return the file path."""
    os.makedirs(output_dir, exist_ok=True)
    date_str = report_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"report-{date_str}-{days}d.md"
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return os.path.abspath(filepath)
